### ISSUE TITLE
Suggestion - Automatically sort at the bottom of the list a checked item

### ISSUE THREAD

**Issue by Kalytis** [Albert221/FastShopping#23] opened 2020-08-04 22:25 UTC
Hi,

It would make the list more readable if, when we check an item on the list, it immediately goes down the list (and then sorted alphabetically ? In the order it's checked ?)

Thanks by advance, love your app !

**Comment by Albert221** [comment] 2020-08-05 04:28
Duplicate of #20.

Thank you!

**Closed by Albert221** 2020-08-05 04:28 UTC
Labels: duplicate
