### ISSUE TITLE
Auto completion/suggestion for new list entries

### ISSUE THREAD

**Issue by dominikheinz** [Albert221/FastShopping#44] opened 2020-12-14 15:28 UTC
Currently, when adding a new item to the shopping list, it is a simple input text box.
It would be really nice to have auto completion/suggestions showing up in a dropdown menu, and updating while typing out the word. Something like this (Excuse my bad paint job):

![export](https://user-images.githubusercontent.com/32770080/102099949-c7fc2c00-3e20-11eb-8ceb-bde9f6429f1e.png)

That would save time if you have to type in shopping items with longer names, - and the app is all about being fast, right? :smile: 
Note: This would require the app to have some sort of dictionary/list of common shopping item names - preferably in various languages (The language could be selected in the settings). An easy start would be to add a list of english grocery items names, and later on expand it for other languages.

**Comment by Albert221** [comment] 2021-01-10 12:06
Thank you for your interest in Fast Shopping!

Although, this is a duplicate of #26.

**Closed by Albert221** 2021-01-10 12:06 UTC
